export interface IWebbingData {
  brands: IBrand[];
}

export interface IBrand {
  name: string;
  webbings: IWebbing[];
}

export interface IWebbing {
  name: string;
  shortName: string;
  colorCode: string;
  stretch: Array<{ kn: number; percent: number }>;
  weight: number;
  priceMeter: { value: number; currency: 'dolar' | 'euro' };
  breakingStrength: number;
  materialType?: 'pes' | 'nylon' | 'dyneema';
  isDiscontinued?: boolean;
}

export function rawData(): IWebbingData {
  return {
    brands: [
      {
        name: 'Slacktivity',
        webbings: [
          {
            name: 'Pinktube',
            shortName: '',
            colorCode: '#6ECFAF',
            stretch: [
              { kn: 1, percent: 1.6 },
              { kn: 2, percent: 6.6 },
              { kn: 3, percent: 10.6 },
              { kn: 4, percent: 13.3 },
              { kn: 5, percent: 15.4 },
              { kn: 6, percent: 17.2 },
              { kn: 7, percent: 18.8 },
              { kn: 8, percent: 20.2 },
              { kn: 9, percent: 21.4 },
              { kn: 10, percent: 22.6 },
              { kn: 11, percent: 23.5 },
              { kn: 12, percent: 24.4 },
              { kn: 13, percent: 25.2 },
              { kn: 14, percent: 26.1 },
              { kn: 15, percent: 26.7 },
              { kn: 16, percent: 27.4 },
              { kn: 17, percent: 28.0 },
              { kn: 18, percent: 28.6 },
              { kn: 19, percent: 29.4 },
              { kn: 20, percent: 30.1 },
            ],
            weight: 48,
            priceMeter: {
              value: 1.68,
              currency: 'euro',
            },
            breakingStrength: 23.6,
            materialType: 'nylon',
          },
          {
            name: 'Redtube',
            shortName: '',
            colorCode: '#A92732',
            stretch: [
              { kn: 1, percent: 1.1 },
              { kn: 2, percent: 3.1 },
              { kn: 3, percent: 6.6 },
              { kn: 4, percent: 9.6 },
              { kn: 5, percent: 11.7 },
              { kn: 6, percent: 13.5 },
              { kn: 7, percent: 14.9 },
              { kn: 8, percent: 16.3 },
              { kn: 9, percent: 17.5 },
              { kn: 10, percent: 18.6 },
              { kn: 11, percent: 19.6 },
              { kn: 12, percent: 20.5 },
              { kn: 13, percent: 21.4 },
              { kn: 14, percent: 22.2 },
              { kn: 15, percent: 22.8 },
              { kn: 16, percent: 23.7 },
              { kn: 17, percent: 24.3 },
              { kn: 18, percent: 24.9 },
              { kn: 19, percent: 25.5 },
              { kn: 20, percent: 26.0 },
            ],
            weight: 76,
            priceMeter: {
              value: 2.49,
              currency: 'euro',
            },
            breakingStrength: 36,
            materialType: 'nylon',
          },
          {
            name: 'Half Marathon',
            shortName: 'H.Marathon',
            colorCode: '#E7F5F8',
            stretch: [
              { kn: 1, percent: 0.3 },
              { kn: 2, percent: 0.5 },
              { kn: 3, percent: 0.8 },
              { kn: 4, percent: 1.1 },
              { kn: 5, percent: 1.6 },
              { kn: 6, percent: 2.1 },
              { kn: 7, percent: 2.7 },
              { kn: 8, percent: 3.4 },
              { kn: 9, percent: 4.0 },
              { kn: 10, percent: 4.6 },
              { kn: 11, percent: 5.2 },
              { kn: 12, percent: 5.8 },
              { kn: 13, percent: 6.3 },
              { kn: 14, percent: 6.8 },
              { kn: 15, percent: 7.2 },
              { kn: 16, percent: 7.7 },
              { kn: 17, percent: 8.0 },
              { kn: 18, percent: 8.4 },
              { kn: 19, percent: 8.9 },
              { kn: 20, percent: 9.2 },
            ],
            weight: 48.5,
            priceMeter: {
              value: 1.79,
              currency: 'euro',
            },
            breakingStrength: 28,
            materialType: 'pes',
          },
          {
            name: 'Y2k',
            shortName: '',
            colorCode: '#07427F',
            stretch: [{ kn: 10, percent: 1 }],
            weight: 33.1,
            priceMeter: {
              value: 1.79,
              currency: 'euro',
            },
            breakingStrength: 34,
            materialType: 'dyneema',
          },
        ],
      },
      {
        name: 'Balance Community',
        webbings: [
          {
            name: 'Feather PRO',
            shortName: 'FeatherPro',
            colorCode: '#13985C',
            stretch: [
              { kn: 1, percent: 0.4 },
              { kn: 2, percent: 1.3 },
              { kn: 3, percent: 2.39 },
              { kn: 4, percent: 3.61 },
              { kn: 5, percent: 4.88 },
              { kn: 6, percent: 6.15 },
              { kn: 7, percent: 7.38 },
              { kn: 8, percent: 8.52 },
              { kn: 9, percent: 9.56 },
              { kn: 10, percent: 10.46 },
              { kn: 11, percent: 11.22 },
              { kn: 12, percent: 11.83 },
              { kn: 13, percent: 12.31 },
              { kn: 14, percent: 12.65 },
              { kn: 15, percent: 12.9 },
              { kn: 16, percent: 13.08 },
              { kn: 17, percent: 13.23 },
              { kn: 18, percent: 13.39 },
              { kn: 19, percent: 13.64 },
              { kn: 20, percent: 14.03 },
            ],
            weight: 51,
            priceMeter: {
              value: 2.6,
              currency: 'dolar',
            },
            breakingStrength: 29,
            materialType: 'pes',
          },
          {
            name: 'Feather',
            shortName: '',
            colorCode: '#67D175',
            stretch: [
              { kn: 1, percent: 0.58 },
              { kn: 2, percent: 1.15 },
              { kn: 3, percent: 2.11 },
              { kn: 4, percent: 3.65 },
              { kn: 5, percent: 5.18 },
              { kn: 6, percent: 6.33 },
              { kn: 7, percent: 7.68 },
              { kn: 8, percent: 8.44 },
              { kn: 9, percent: 9.4 },
              { kn: 10, percent: 10.36 },
            ],
            weight: 20,
            priceMeter: {
              value: 1.6,
              currency: 'dolar',
            },
            breakingStrength: 20,
            materialType: 'pes',
          },
          {
            name: 'Mantra MK4',
            shortName: 'Mantra4',
            colorCode: '#3D3A79',
            stretch: [
              { kn: 1, percent: 0.26 },
              { kn: 2, percent: 0.56 },
              { kn: 3, percent: 0.92 },
              { kn: 4, percent: 1.33 },
              { kn: 5, percent: 1.78 },
              { kn: 6, percent: 2.26 },
              { kn: 7, percent: 2.75 },
              { kn: 8, percent: 3.25 },
              { kn: 9, percent: 3.73 },
              { kn: 10, percent: 4.21 },
              { kn: 11, percent: 4.67 },
              { kn: 12, percent: 5.11 },
              { kn: 13, percent: 5.52 },
              { kn: 14, percent: 5.9 },
              { kn: 15, percent: 6.25 },
              { kn: 16, percent: 6.57 },
              { kn: 17, percent: 6.87 },
              { kn: 18, percent: 7.15 },
              { kn: 19, percent: 7.41 },
              { kn: 20, percent: 7.65 },
            ],
            weight: 76,
            priceMeter: {
              value: 2.4,
              currency: 'dolar',
            },
            breakingStrength: 42,
            materialType: 'pes',
          },
          {
            name: 'Lift',
            shortName: '',
            colorCode: '#DF6F25',
            stretch: [
              { kn: 1, percent: 2.37 },
              { kn: 2, percent: 4.87 },
              { kn: 3, percent: 7.11 },
              { kn: 4, percent: 9.11 },
              { kn: 5, percent: 10.9 },
              { kn: 6, percent: 12.51 },
              { kn: 7, percent: 13.94 },
              { kn: 8, percent: 15.22 },
              { kn: 9, percent: 16.37 },
              { kn: 10, percent: 17.4 },
              { kn: 11, percent: 18.33 },
              { kn: 12, percent: 19.16 },
              { kn: 13, percent: 19.92 },
              { kn: 14, percent: 20.61 },
              { kn: 15, percent: 21.25 },
              { kn: 16, percent: 21.84 },
              { kn: 17, percent: 22.38 },
              { kn: 18, percent: 22.89 },
              { kn: 19, percent: 23.37 },
              { kn: 20, percent: 23.83 },
            ],
            weight: 58,
            priceMeter: {
              value: 2.8,
              currency: 'dolar',
            },
            breakingStrength: 28,
            materialType: 'pes',
          },
        ],
      },
      {
        name: 'Raed Slacklines',
        webbings: [
          {
            name: 'MOTM',
            shortName: '',
            colorCode: '#A70024',
            stretch: [
              { kn: 1, percent: 4 },
              { kn: 2, percent: 6 },
              { kn: 3, percent: 7.8 },
              { kn: 4, percent: 9.8 },
              { kn: 5, percent: 11.5 },
              { kn: 6, percent: 13 },
              { kn: 7, percent: 14.5 },
              { kn: 8, percent: 15.5 },
              { kn: 9, percent: 16.2 },
              { kn: 10, percent: 17 },
              { kn: 11, percent: 17.8 },
              { kn: 12, percent: 18.5 },
              { kn: 13, percent: 19.3 },
              { kn: 14, percent: 20 },
              { kn: 15, percent: 20.5 },
              { kn: 16, percent: 21 },
              { kn: 17, percent: 21.5 },
              { kn: 18, percent: 22.1 },
              { kn: 19, percent: 22.8 },
              { kn: 20, percent: 23.5 },
            ],
            weight: 56,
            priceMeter: {
              value: 1.49,
              currency: 'euro',
            },
            breakingStrength: 27,
            materialType: 'nylon',
          },
          {
            name: 'Rainbow',
            shortName: '',
            colorCode: '#D7F10E',
            stretch: [
              { kn: 1, percent: 0.3 },
              { kn: 2, percent: 0.6 },
              { kn: 3, percent: 0.8 },
              { kn: 4, percent: 1.2 },
              { kn: 5, percent: 1.5 },
              { kn: 6, percent: 2.2 },
              { kn: 7, percent: 3.1 },
              { kn: 8, percent: 4.4 },
              { kn: 9, percent: 5.6 },
              { kn: 10, percent: 6.8 },
              { kn: 11, percent: 7.6 },
              { kn: 12, percent: 8.4 },
              { kn: 14, percent: 9.8 },
              { kn: 16, percent: 10.5 },
              { kn: 18, percent: 11.4 },
              { kn: 20, percent: 12 },
            ],
            weight: 62,
            priceMeter: {
              value: 1.65,
              currency: 'euro',
            },
            breakingStrength: 36,
            materialType: 'pes',
          },
          {
            name: 'Helium',
            shortName: '',
            colorCode: '#D8D8D8',
            stretch: [
              { kn: 1, percent: 0.3 },
              { kn: 2, percent: 0.6 },
              { kn: 3, percent: 1.2 },
              { kn: 4, percent: 1.5 },
              { kn: 5, percent: 2 },
              { kn: 6, percent: 2.4 },
              { kn: 7, percent: 2.8 },
              { kn: 8, percent: 3.3 },
              { kn: 9, percent: 3.8 },
              { kn: 10, percent: 4.4 },
              { kn: 11, percent: 5 },
              { kn: 12, percent: 5.5 },
              { kn: 13, percent: 6 },
              { kn: 14, percent: 6.4 },
              { kn: 15, percent: 6.8 },
              { kn: 16, percent: 7.3 },
              { kn: 17, percent: 7.7 },
              { kn: 18, percent: 8.2 },
              { kn: 19, percent: 8.6 },
              { kn: 20, percent: 9.1 },
            ],
            weight: 38,
            priceMeter: {
              value: 0.69,
              currency: 'euro',
            },
            breakingStrength: 24,
            materialType: 'pes',
          },
          {
            name: 'Parsec',
            shortName: '',
            colorCode: '#0F0F16',
            stretch: [
              { kn: 1, percent: 0.25 },
              { kn: 2, percent: 0.5 },
              { kn: 3, percent: 0.85 },
              { kn: 4, percent: 1.2 },
              { kn: 5, percent: 1.6 },
              { kn: 6, percent: 2.0 },
              { kn: 7, percent: 2.6 },
              { kn: 8, percent: 3.2 },
              { kn: 9, percent: 3.9 },
              { kn: 10, percent: 4.5 },
              { kn: 11, percent: 5 },
              { kn: 12, percent: 5.6 },
              { kn: 13, percent: 6 },
              { kn: 14, percent: 6.5 },
              { kn: 15, percent: 6.9 },
              { kn: 16, percent: 7.4 },
              { kn: 17, percent: 7.6 },
              { kn: 18, percent: 7.8 },
              { kn: 19, percent: 8.1 },
              { kn: 20, percent: 8.5 },
            ],
            weight: 59,
            priceMeter: {
              value: 0.99,
              currency: 'euro',
            },
            breakingStrength: 33,
            materialType: 'pes',
          },
        ],
      },
      {
        name: 'Aki Slacklines',
        webbings: [
          {
            name: 'Sonic 2',
            shortName: '',
            colorCode: '#D59E2A',
            stretch: [
              { kn: 2, percent: 2.6 },
              { kn: 3, percent: 4.6 },
              { kn: 4, percent: 7.3 },
              { kn: 5, percent: 9.3 },
              { kn: 6, percent: 10.8 },
              { kn: 7, percent: 12.0 },
              { kn: 8, percent: 13.1 },
              { kn: 9, percent: 14.1 },
              { kn: 10, percent: 15.0 },
            ],
            weight: 69,
            priceMeter: {
              value: 1.99,
              currency: 'euro',
            },
            breakingStrength: 35,
            materialType: 'nylon',
          },
          {
            name: 'Unicorn',
            shortName: '',
            colorCode: '#9FBD73',
            stretch: [
              { kn: 2, percent: 1.1 },
              { kn: 3, percent: 1.7 },
              { kn: 4, percent: 2.3 },
              { kn: 5, percent: 3.2 },
              { kn: 6, percent: 4.5 },
              { kn: 7, percent: 6.0 },
              { kn: 8, percent: 7.3 },
              { kn: 9, percent: 8.2 },
              { kn: 10, percent: 9.0 },
            ],
            weight: 61,
            priceMeter: {
              value: 1.79,
              currency: 'euro',
            },
            breakingStrength: 32,
            materialType: 'pes',
          },
          {
            name: 'Voyage',
            shortName: '',
            colorCode: '#1CB0E4',
            stretch: [
              { kn: 2, percent: 0.6 },
              { kn: 3, percent: 0.9 },
              { kn: 4, percent: 1.2 },
              { kn: 5, percent: 1.5 },
              { kn: 6, percent: 1.9 },
              { kn: 7, percent: 2.3 },
              { kn: 8, percent: 3.1 },
              { kn: 9, percent: 3.7 },
              { kn: 10, percent: 4.4 },
            ],
            weight: 55,
            priceMeter: {
              value: 1.69,
              currency: 'euro',
            },
            breakingStrength: 33,
            materialType: 'pes',
          },
          {
            name: 'White Magic',
            shortName: 'w.magic',
            colorCode: '#FFFFFF',
            stretch: [
              { kn: 2, percent: 0.7 },
              { kn: 3, percent: 1.1 },
              { kn: 4, percent: 1.5 },
              { kn: 5, percent: 1.9 },
              { kn: 6, percent: 2.4 },
              { kn: 7, percent: 2.9 },
              { kn: 8, percent: 3.6 },
              { kn: 9, percent: 4.4 },
              { kn: 10, percent: 5.1 },
            ],
            weight: 61,
            priceMeter: {
              value: 1.19,
              currency: 'euro',
            },
            breakingStrength: 34,
            materialType: 'pes',
          },
        ],
      },
      {
        name: 'Equilibrium',
        webbings: [
          {
            name: 'Dragon',
            shortName: '',
            colorCode: '#2D77C0',
            stretch: [
              { kn: 2.5, percent: 3 },
              { kn: 5, percent: 4 },
              { kn: 10, percent: 6 },
              { kn: 15, percent: 8 },
            ],
            weight: 64,
            priceMeter: {
              value: 1.09,
              currency: 'euro',
            },
            breakingStrength: 31,
            materialType: 'pes',
          },
          {
            name: 'Element',
            shortName: '',
            colorCode: '#C8811C',
            stretch: [
              { kn: 2.5, percent: 7 },
              { kn: 5, percent: 11 },
              { kn: 10, percent: 16 },
              { kn: 15, percent: 19 },
            ],
            weight: 42,
            priceMeter: {
              value: 1.2,
              currency: 'euro',
            },
            breakingStrength: 20,
            materialType: 'nylon',
          },
          {
            name: 'Fresh',
            shortName: '',
            colorCode: '#724483',
            stretch: [
              { kn: 5, percent: 8 },
              { kn: 10, percent: 11 },
              { kn: 15, percent: 16 },
              { kn: 20, percent: 18 },
            ],
            weight: 67,
            priceMeter: {
              value: 1.76,
              currency: 'euro',
            },
            breakingStrength: 32,
            materialType: 'nylon',
          },
        ],
      },
      {
        name: 'Slack.fr',
        webbings: [
          {
            name: 'Mcfly',
            shortName: '',
            colorCode: '#BB1461',
            stretch: [
              { kn: 5, percent: 8.5 },
              { kn: 10, percent: 12.5 },
              { kn: 15, percent: 14.5 },
            ],
            weight: 65,
            priceMeter: {
              value: 2.29,
              currency: 'euro',
            },
            breakingStrength: 31,
            materialType: 'nylon',
            isDiscontinued: true,
          },
          {
            name: 'Moonwalk',
            shortName: '',
            colorCode: '#F37F61',
            stretch: [
              { kn: 5, percent: 2.4 },
              { kn: 10, percent: 4 },
              { kn: 15, percent: 4.4 },
              { kn: 20, percent: 5 },
            ],
            weight: 33.4,
            priceMeter: {
              value: 3.4,
              currency: 'euro',
            },
            breakingStrength: 35,
            materialType: 'dyneema',
            isDiscontinued: true,
          },
        ],
      },
      {
        name: 'Elephant',
        webbings: [
          {
            name: 'Bluewing',
            shortName: '',
            colorCode: '#187EC2',
            stretch: [
              { kn: 1, percent: 0.5 },
              { kn: 2, percent: 1 },
              { kn: 3, percent: 1.6 },
              { kn: 4, percent: 2.5 },
              { kn: 5, percent: 3.2 },
              { kn: 6, percent: 4 },
              { kn: 7, percent: 6.1 },
              { kn: 8, percent: 8 },
              { kn: 9, percent: 10 },
              { kn: 10, percent: 11 },
              { kn: 11, percent: 12.3 },
              { kn: 12, percent: 13 },
              { kn: 13, percent: 13.6 },
              { kn: 14, percent: 14 },
              { kn: 15, percent: 14.5 },
              { kn: 16, percent: 15 },
              { kn: 17, percent: 15.3 },
              { kn: 18, percent: 15.8 },
              { kn: 19, percent: 16.1 },
              { kn: 20, percent: 16.5 },
            ],
            weight: 63,
            priceMeter: {
              value: 1.49,
              currency: 'euro',
            },
            breakingStrength: 30,
            materialType: 'pes',
            isDiscontinued: true,
          },
          {
            name: 'Passion',
            shortName: '',
            colorCode: '#C51429',
            stretch: [
              { kn: 2, percent: 3.5 },
              { kn: 4, percent: 6.5 },
              { kn: 6, percent: 9.0 },
              { kn: 8, percent: 10.8 },
              { kn: 10, percent: 12.3 },
              { kn: 12, percent: 13.5 },
              { kn: 14, percent: 14.5 },
              { kn: 16, percent: 15.3 },
              { kn: 18, percent: 16.1 },
              { kn: 20, percent: 16.9 },
            ],
            weight: 69,
            priceMeter: {
              value: 1.88,
              currency: 'euro',
            },
            breakingStrength: 33,
            materialType: 'nylon',
            isDiscontinued: true,
          },
        ],
      },
    ],
  };
}
